arch = { packages = [
  "accountsservice",
  "alacritty",
  "alsa-firmware",
  "alsa-plugins",
  "alsa-utils",
  "appmenu-gtk-module",
  "awesome-terminal-fonts",
  "base",
  "base-devel",
  "bash-completion",
  "bind",
  "bluez",
  "bluez-hid2hci",
  "bluez-libs",
  "bluez-obex",
  "bluez-utils",
  "bpftune-git",
  "brew-git",
  "btop",
  "btrfs-assistant",
  "btrfs-progs",
  "bun",
  "cachy-update",
  "cachyos-fish-config",
  "cachyos-gaming-applications",
  "cachyos-gaming-meta",
  "cachyos-hello",
  "cachyos-hooks",
  "cachyos-kernel-manager",
  "cachyos-keyring",
  "cachyos-micro-settings",
  "cachyos-mirrorlist",
  "cachyos-packageinstaller",
  "cachyos-plymouth-bootanimation",
  "cachyos-plymouth-theme",
  "cachyos-rate-mirrors",
  "cachyos-settings",
  "cachyos-snapper-support",
  "cachyos-v3-mirrorlist",
  "cachyos-v4-mirrorlist",
  "cachyos-wallpapers",
  "cantarell-fonts",
  "chezmoi",
  "chwd",
  "cosmic-app-library",
  "cosmic-applets",
  "cosmic-bg",
  "cosmic-comp",
  "cosmic-files",
  "cosmic-greeter",
  "cosmic-icon-theme",
  "cosmic-launcher",
  "cosmic-monitor",
  "cosmic-notifications",
  "cosmic-osd",
  "cosmic-panel",
  "cosmic-player",
  "cosmic-randr",
  "cosmic-screenshot",
  "cosmic-session",
  "cosmic-settings",
  "cosmic-settings-daemon",
  "cosmic-terminal",
  "cosmic-text-editor",
  "cosmic-wallpapers",
  "cosmic-workspaces",
  "cpupower",
  "cryptsetup",
  "cups",
  "cups-filters",
  "cups-pdf",
  "device-mapper",
  "diffutils",
  "dmemcg-booster",
  "dmidecode",
  "dmraid",
  "dnsmasq",
  "docker",
  "docker-compose",
  "dosfstools",
  "duf",
  "e2fsprogs",
  "efibootmgr",
  "efitools",
  "egl-wayland",
  "ethtool",
  "exfatprogs",
  "f2fs-tools",
  "fastfetch",
  "fcitx5",
  "fcitx5-configtool",
  "fcitx5-gtk",
  "fcitx5-qt",
  "ffmpegthumbnailer",
  "firefox",
  "flatpak",
  "foomatic-db",
  "foomatic-db-engine",
  "foomatic-db-gutenprint-ppds",
  "foomatic-db-nonfree",
  "foomatic-db-nonfree-ppds",
  "foomatic-db-ppds",
  "fsarchiver",
  "fuse2",
  "gearlever",
  "ghostscript",
  "ghostty",
  "git",
  "git-zsh-completion",
  "github-cli",
  "glances",
  "gnome-keyring",
  "google-chrome",
  "gsfonts",
  "gst-libav",
  "gst-plugin-pipewire",
  "gst-plugin-va",
  "gst-plugins-bad",
  "gst-plugins-ugly",
  "gutenprint",
  "hdparm",
  "hplip",
  "hwdetect",
  "hwinfo",
  "inetutils",
  "intel-media-driver",
  "intel-ucode",
  "iwd",
  "jfsutils",
  "less",
  "lib32-nvidia-utils",
  "lib32-opencl-nvidia",
  "lib32-vulkan-icd-loader",
  "lib32-vulkan-intel",
  "libdbusmenu-glib",
  "libdvdcss",
  "libgsf",
  "libopenraw",
  "libva-nvidia-driver",
  "limine",
  "limine-mkinitcpio-hook",
  "limine-snapper-sync",
  "linux-cachyos",
  "linux-cachyos-headers",
  "linux-cachyos-lts",
  "linux-cachyos-lts-headers",
  "linux-cachyos-lts-nvidia-open",
  "linux-cachyos-nvidia-open",
  "linux-firmware",
  "logrotate",
  "lsb-release",
  "lsscsi",
  "lvm2",
  "man-db",
  "man-pages",
  "mdadm",
  "meld",
  "mesa-utils",
  "metapac",
  "micro",
  "mkinitcpio",
  "modemmanager",
  "mtools",
  "nano",
  "nano-syntax-highlighting",
  "netctl",
  "networkmanager",
  "networkmanager-openvpn",
  "nfs-utils",
  "nilfs-utils",
  "notification-daemon",
  "noto-fonts",
  "noto-fonts-cjk",
  "noto-fonts-emoji",
  "nss-mdns",
  "nvidia-prime",
  "nvidia-settings",
  "nvidia-utils",
  "oh-my-zsh-git",
  "opencl-nvidia",
  "opencode",
  "openssh",
  "os-prober",
  "pacman-contrib",
  "paru",
  "pavucontrol",
  "perl",
  "pipewire-alsa",
  "pipewire-pulse",
  "pkgfile",
  "plocate",
  "plymouth",
  "poppler-glib",
  "power-profiles-daemon",
  "profile-sync-daemon",
  "pv",
  "python",
  "python-defusedxml",
  "python-packaging",
  "python-pyqt5",
  "python-reportlab",
  "rbenv",
  "realtime-privileges",
  "rebuild-detector",
  "reflector",
  "ripgrep",
  "rsync",
  "ruby-build",
  "rust",
  "s-nail",
  "sg3_utils",
  "shelly",
  "shelly-flatpak-backend",
  "smartmontools",
  "snapper",
  "sof-firmware",
  "stow",
  "sudo",
  "switcheroo-control",
  "sysfsutils",
  "system-config-printer",
  "texinfo",
  "topgrade",
  "tree",
  "ttf-bitstream-vera",
  "ttf-dejavu",
  "ttf-liberation",
  "ttf-meslo-nerd",
  "ttf-opensans",
  "ufw",
  "ufw-extras",
  "unrar",
  "unzip",
  "upower",
  "usb_modeswitch",
  "usbutils",
  "uv",
  "vim",
  "vlc-plugins-all",
  "vpl-gpu-rt",
  "vulkan-icd-loader",
  "vulkan-intel",
  "wget",
  "which",
  "winboat",
  "wireplumber",
  "wl-clipboard",
  "wpa_supplicant",
  "xclip",
  "xdg-desktop-portal-cosmic",
  "xdg-desktop-portal-gtk",
  "xdg-user-dirs",
  "xfsprogs",
  "xl2tpd",
  "xorg-xwayland",
  "zed",
  "zsh-autocomplete",
  "zsh-doc",
  "zsh-lovers",
] }
flatpak = { repos = [
  { name = "system:flathub", options = { url = "https://dl.flathub.org/repo/" } },
] }
